### PR TITLE
(Remove) Google fonts

### PR DESCRIPTION
**Pull request by Roardom**
Why, just why.

### CODE REVIEW

**Comment by HDVinnie** [comment]
`resources/sass/main/aboutus.scss` is not even used anymore...

**Comment by Roardom** [comment]
How on earth is the network call for this font still showing up in dev console then?

**Comment by Roardom** [comment]
Unless you're meaning we should just get rid of aboutus.scss completely, which was on my list of things to do next.

**Comment by HDVinnie** [comment]
I mean the file is there and compiled in aboutus.scss but its not actually used anywhere anymore since your css/views refactor. So this PR could just remove the aboutus.scss and remove the import in app.scss

**Pull request merged**
