### PR TITLE
(Update) TorrentController

### PR DESCRIPTION
**Pull request by innocente205**
Ensure minimum length padded IMDB number

### CODE REVIEW

**Comment by Roardom** [comment]
I've already made the necessary adjustments in https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/2347 and https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/2249 to be able to store imdb ids as an integer and not have to worry about zero padding. We plan to convert all id columns to integers in the future as well. What issue are you facing that requires zero padding?

**Comment by innocente205** [comment]
https://www.imdb.com/title/tt88511/

results in a 404

https://www.imdb.com/title/tt0088511/

serves the page.

**Comment by Roardom** [comment]
In which view are these incorrect links being shown?

**Comment by innocente205** [comment]
No, I see now that you've corrected the problem a different way. Please go ahead and disregard this update.

**Pull request closed without merging**
