### PR TITLE
(Feature) Add more Buff options for Freeleech

### PR DESCRIPTION
**Pull request by Obi-Wana**
### Allows User to set FL from 0% to 100% (in 25% steps).
- Added new "X% Free Icons" for torrent-search, graveyard-search & torrent.blade views.
- Added it to Announce Process Jobs

<a href="https://ibb.co/Bnbc5Tw"></a>

### ToDo's:
- [x] Move all BUFF features from "TorrentController" into "TorrentBuffController"

### CODE REVIEW

**Comment by kis2a** [comment]
add this 25 / 50 / .... to upload page and permissions to group (visible oir not visible) 

add this in sitpot , multiple sitpot , and X poin t required !  

ex :  freeleech 24h for 15000 point
       50% for 48h for 10000 point
       25% for 96h for 5000 point 

add variable in staff panel , to manage groupe to see this in upload page
      *is add groupe permission in staffcp (visible for x group ) i view or not ((25/50/100/x2) in upload page 
add menu to staffCP to manage sitpot 
      *select sitpot cat (25/50/100/x2)
      *Select time for sitpot (25%=96h  /50%=48/  100%=24h x2=18h ) (is exemple for manage this to staffcp)

**Comment by HDVinnie** [comment]
> add this 25 / 50 / .... to upload page and permissions to group (visible oir not visible)
> 
> add this in sitpot , multiple sitpot , and X poin t required !
> 
> ex : freeleech 24h for 15000 point 50% for 48h for 10000 point 25% for 96h for 5000 point
> 
> add variable in staff panel , to manage groupe to see this in upload page *is add groupe permission in staffcp (visible for x group ) i view or not ((25/50/100/x2) in upload page add menu to staffCP to manage sitpot *select sitpot cat (25/50/100/x2) *Select time for sitpot (25%=96h /50%=48/ 100%=24h x2=18h ) (is exemple for manage this to staffcp)

Maybe in the future but is not planned for this Pull Request

**Comment by Obi-Wana** [comment]
@HDVinnie 
Do we want to update before releasing:
- API (add flags for partial FL)
- API Docs
- NerdBot Messages (distinct between 1% and 100% FL for the "There are X FreeLeech..." ?)
- Set FL on upload using the GUI, might be an issue as it sets the value to "1" instead of 100 when setting to "Yes".

**Comment by HDVinnie** [comment]
> @HDVinnie Do we want to update before releasing:
> 
> * API (add flags for partial FL)
> * API Docs
> * NerdBot Messages (distinct between 1% and 100% FL for the "There are X FreeLeech..." ?)
> * Set FL on upload using the GUI, might be an issue as it sets the value to "1" instead of 100 when setting to "Yes".

Nerdbot is done : https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/2036/commits/a04eedd7b84b4145539491c90dcac5b36222f2f5

Upload page for staff/internals is done: https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/2036/commits/d73361477b1ce20a9faa020dc9ff1c6eea862380

API is done: https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/2036/commits/791d0fe25d82769b312fa6c49d196759bcd9331d

https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/2036/commits/c39018a15a66363b935d870ee3a3a9ae520e3dd5

Everything commit wise is here for the v6.x.x branch->v6.0.0 PR 
https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/2036

**Pull request merged**
