### PR TITLE
(Update) Spanish Translation

### PR DESCRIPTION
**Pull request by Deci8BelioS**

### CODE REVIEW

**Comment by Deci8BelioS** [comment]
Hi, I have seen that in the branch “8.x.x” some .php files of the English have not been added

**Comment by Roardom** [comment]
> Hi, I have seen that in the branch “8.x.x” some .php files of the Spanish have not been added

Not all files have been translated yet. Feel free to copy the English file into the Spanish directory as a starting point :slightly_smiling_face:

**Comment by Deci8BelioS** [comment]
> > Hi, I have seen that in the branch “8.x.x” some .php files of the Spanish have not been added
> 
> Not all files have been translated yet. Feel free to copy the English file into the Spanish directory as a starting point 🙂

I translated all the .php files that were in the English language folder (keeping the Spanish translations that I had compared line by line) from the main branch.

**Comment by Roardom** [comment]
> > > Hi, I have seen that in the branch “8.x.x” some .php files of the Spanish have not been added
> > 
> > 
> > Not all files have been translated yet. Feel free to copy the English file into the Spanish directory as a starting point 🙂
> 
> I translated all the .php files that were in the English language folder (keeping the Spanish translations that I had compared line by line) from the main branch.

Some .blade.php files have hardcoded English text as they haven't been translated yet. In this case, you might have to swap out the hardcoded text for e.g. `{{ __('file.key') }}`, and then add the key to the English and Spanish directories.

**Comment by Deci8BelioS** [comment]
> > > > Hi, I have seen that in the branch “8.x.x” some .php files of the Spanish have not been added
> > > 
> > > 
> > > Not all files have been translated yet. Feel free to copy the English file into the Spanish directory as a starting point 🙂
> > 
> > 
> > I translated all the .php files that were in the English language folder (keeping the Spanish translations that I had compared line by line) from the main branch.
> 
> Some .blade.php files have hardcoded English text as they haven't been translated yet. In this case, you might have to swap out the hardcoded text for e.g. `{{ __('file.key') }}`, and then add the key to the English and Spanish directories.

I have translated the files in the /lang/en/ folder and there were files in that folder that were not in /lang/en/ and I added them already translated but they have not been added to the 8.x.x branch.

**Comment by Roardom** [comment]
> I have translated the files in the /lang/en/ folder and there were files in that folder that were not in /lang/es/ and I added them already translated but they have not been added to the 8.x.x branch.

Sorry, I'm confused which problem you're experiencing. Can you provide an example?

**Comment by Deci8BelioS** [comment]
> > I have translated the files in the /lang/en/ folder and there were files in that folder that were not in /lang/es/ and I added them already translated but they have not been added to the 8.x.x branch.
> 
> Sorry, I'm confused which problem you're experiencing. Can you provide an example?

In the 8.x.x branch the php files in the /lang/en/ folder were updated from my fork, but the files marked as + in green shown in the screenshot I sent, which are many translated strings, have not been added.

**Comment by Roardom** [comment]
I think I see now. You cloned the `master` branch but your pull request is requesting to merge into the `8.x.x` branch. You will have to switch to the `8.x.x` branch in your repo (`git switch 8.x.x`) and cherry-pick the commits you made on your `master` branch to your `8.x.x` branch (`git cherry-pick <commit hash>`). Then probably create a new pull request from that branch.

**Comment by Deci8BelioS** [comment]
> I think I see now. You cloned the `master` branch but your pull request is requesting to merge into the `8.x.x` branch. You will have to switch to the `8.x.x` branch in your repo (`git switch 8.x.x`) and cherry-pick the commits you made on your `master` branch to your `8.x.x` branch (`git cherry-pick <commit hash>`). Then probably create a new pull request from that branch.

I have already cloned the 8.x.x branch and made the relevant changes and sent the pull request

**Pull request closed without merging**
