### PR TITLE
(Enhancement) New options on torrent upload api

### PR DESCRIPTION
**Pull request by PyR8zdl**
Adds options to set torrent as Featured, DoubleUp, Freeleech, and Sticky on upload api endpoint.

I've done limited testing on this and I'm worndering if this could be done better.

### CODE REVIEW

**Comment by PyR8zdl** [comment]
Ok, I think I got this mostly tested. I want to test a few more scenarios tomorrow.

**Comment by PyR8zdl** [comment]
I've tested with all possible options and is working as intended. Hopefully, all the checks pass. 👍

**Comment by HDVinnie** [comment]
> I've tested with all possible options and is working as intended. Hopefully, all the checks pass. 👍

It won't pass TravisCI until the test is updated. https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/tests/Feature/Http/Controllers/API/TorrentControllerTest.php

If you cannot do it then I will this weekend before merging.

**Comment by HDVinnie** [comment]
@PyR8zdl I have simplified the if else to ternary and updated the test. Assuming it passes ill merge.

**Comment by PyR8zdl** [comment]
@HDVinnie Nice, It looks alot better now. In future I will use this format. Thanks!

**Pull request merged**
