### PR TITLE
(udpate) 2FA using TOTP instead of Mail

### PR DESCRIPTION
**Pull request by Obi-Wana**
Adding the basic functionality for 2FA using TOTP Token (supporting any TOTP App like Google Authenticator).
Creates /totp Route and displays QR Codes & TOTP Token to be added in 2FA Apps.

2FA replaces the current "TwoStep" feature.

### CODE REVIEW

**Comment by Obi-Wana** [comment]
fixed all BUT 1 styleCI error. dont know how to resolve the last one.

**Comment by HDVinnie** [comment]
Going to review this very soon. Just a quick question. Is there no recovery keys options?

**Comment by Obi-Wana** [comment]
> Going to review this very soon. Just a quick question. Is there no recovery keys options?

no, theres no automated recovery Option yet.
The problem with that is, some users may have used temporary email addresses and i did not want to send a new token to that email address.

whats your opinion on that?

**Comment by SeeTwoArrr** [comment]
Just an FYI: Enabling this 2FA breaks Jackett support for the tracker.

**Comment by Obi-Wana** [comment]
i gonna take a look at: [https://github.com/antonioribeiro/recovery](https://github.com/antonioribeiro/recovery) for recovery code option.

**Comment by HDVinnie** [comment]
@Obi-Wana it might be worth looking into https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions/1481

**Comment by Obi-Wana** [comment]
> @Obi-Wana it might be worth looking into #1481

@HDVinnie been looking at this recently. 
think best is to close this PR for now as the whole auth mechanics will change soon?

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions/1481

**Pull request closed without merging**
