### PR TITLE
(Feature) Auth logging

### PR DESCRIPTION
**Pull request by HDVinnie**
- TODO:
-- Controllers
-- Views
-- Trust / Untrust Devices
-- Notify User Via Email When New Device Tries To Login To Account
```
>>> $user = App\Models\User::with(['authentications', 'devices'])->whereId(3)->first();
=> App\Models\User {#3807
     id: 3,
     username: "UNIT3D",
     group_id: 10,
     active: 1,
     uploaded: 0,
     downloaded: 0,
     image: null,
     title: null,
     about: null,
     signature: null,
     fl_tokens: 0,
     seedbonus: 0.0,
     invites: 0,
     hitandruns: 0,
     chatroom_id: 1,
     censor: 0,
     chat_hidden: 0,
     hidden: 0,
     style: 0,
     nav: 0,
     torrent_layout: 0,
     torrent_filters: 0,
     custom_css: null,
     ratings: 0,
     read_rules: 1,
     can_chat: 1,
     can_comment: 1,
     can_download: 1,
     can_request: 1,
     can_invite: 1,
     can_upload: 1,
     show_poster: 0,
     peer_hidden: 0,
     private_profile: 0,
     block_notifications: 0,
     stat_hidden: 0,
     twostep: 0,
     last_login: "2020-03-07 23:09:12",
     last_action: "2020-03-07 23:09:20",
     disabled_at: null,
     deleted_by: null,
     created_at: "2020-03-03 20:34:41",
     updated_at: "2020-03-07 23:09:20",
     locale: "en",
     chat_status_id: 1,
     deleted_at: null,
     authentications: Illuminate\Database\Eloquent\Collection {#3813
       all: [
         App\Models\Authentication {#3817
           id: 1,
           username: "UNIT3D",
           ip_address: "192.168.10.1",
           type: "login",
           user_id: 3,
           device_id: 1,
           created_at: "2020-03-07 22:56:25",
           updated_at: "2020-03-07 22:56:25",
         },
         App\Models\Authentication {#3818
           id: 2,
           username: "UNIT3D",
           ip_address: "192.168.10.1",
           type: "login",
           user_id: 3,
           device_id: 1,
           created_at: "2020-03-07 22:57:52",
           updated_at: "2020-03-07 22:57:52",
         },
         App\Models\Authentication {#3819
           id: 3,
           username: "UNIT3D",
           ip_address: "192.168.10.1",
           type: "failed",
           user_id: 3,
           device_id: 1,
           created_at: "2020-03-07 23:01:09",
           updated_at: "2020-03-07 23:01:09",
         },
         App\Models\Authentication {#3820
           id: 4,
           username: "UNIT3D",
           ip_address: "192.168.10.1",
           type: "login",
           user_id: 3,
           device_id: 1,
           created_at: "2020-03-07 23:01:16",
           updated_at: "2020-03-07 23:01:16",
         },
         App\Models\Authentication {#3821
           id: 5,
           username: "UNIT3D",
           ip_address: "192.168.10.1",
           type: "failed",
           user_id: 3,
           device_id: 1,
           created_at: "2020-03-07 23:03:19",
           updated_at: "2020-03-07 23:03:19",
         },
         App\Models\Authentication {#3822
           id: 6,
           username: "UNIT3D",
           ip_address: "192.168.10.1",
           type: "failed",
           user_id: 3,
           device_id: 1,
           created_at: "2020-03-07 23:03:27",
           updated_at: "2020-03-07 23:03:27",
         },
         App\Models\Authentication {#3823
           id: 7,
           username: "UNIT3D",
           ip_address: "192.168.10.1",
           type: "failed",
           user_id: 3,
           device_id: 1,
           created_at: "2020-03-07 23:03:33",
           updated_at: "2020-03-07 23:03:33",
         },
         App\Models\Authentication {#3824
           id: 8,
           username: "UNIT3D",
           ip_address: "192.168.10.1",
           type: "login",
           user_id: 3,
           device_id: 2,
           created_at: "2020-03-07 23:09:13",
           updated_at: "2020-03-07 23:09:13",
         },
       ],
     },
     devices: Illuminate\Database\Eloquent\Collection {#3812
       all: [
         App\Models\Device {#3775
           id: 1,
           user_id: 3,
           platform: "OS X",
           platform_version: "10_14_6",
           browser: "Safari",
           browser_version: "12.1.2",
           language: "en-us",
           is_desktop: 1,
           is_mobile: 0,
           is_trusted: 0,
           is_untrusted: 0,
           created_at: "2020-03-07 22:43:22",
           updated_at: "2020-03-07 22:43:22",
         },
         App\Models\Device {#3811
           id: 2,
           user_id: 3,
           platform: "OS X",
           platform_version: "10.14",
           browser: "Firefox",
           browser_version: "63.0",
           language: "en-us",
           is_desktop: 1,
           is_mobile: 0,
           is_trusted: 0,
           is_untrusted: 0,
           created_at: "2020-03-07 23:09:13",
           updated_at: "2020-03-07 23:09:13",
         },
       ],
     },
   }
```

### CODE REVIEW

**Comment by HDVinnie** [comment]
@gyakkun have a review and let me know what you think so far.

**Comment by HDVinnie** [comment]
Ok seeing as I have not heard from @gyakkun I'm going to continue this on my own.

**Comment by gyakkun** [comment]
Sorry for breaking my promise... Im recently  busy with some nCoV stuff and now in an intern so no much time counld be spend on UNIT3D and a big thanks to you for accepting my proposal. I'll try my best to catch up your code.

**Comment by HDVinnie** [comment]
It's fine. Life comes first.

**Comment by HDVinnie** [comment]
[](https://postimg.cc/YL1WdV7t)

Should be done this week for beta testing.

**Pull request closed without merging**
