### PR TITLE
(Fix) Various invite tree fixes

### PR DESCRIPTION
**Pull request by Roardom**
Average seedtime is now average and not total. Swap tree stats of seedsize vs seedtime. Use correct user for last action. Filter out infinite ratios.

### CODE REVIEW

**Comment by Audionut** [comment]
Ancestors should not be viewable to user accounts IMO.

**Comment by Roardom** [comment]
> Ancestors should not be viewable to user accounts IMO.

I consulted multiple staffers and they all agreed in having transparency.

**Comment by Audionut** [comment]
Transparency for what, exactly?

**Comment by Roardom** [comment]
> Transparency for what, exactly?

To see the full dependency chain of who's trusting you to be a good user.

Also a reminder that other tracker software such as the one you used also showed everyone's inviter on their profile page for anyone to view.

**Comment by Audionut** [comment]
They don't show up in the tree. Why on earth does anyone need to see who is depending on them being a good user.

**Comment by Audionut** [comment]
MiM also suggests that the amount of levels down that can be seen should be tied to a perk.

**Pull request merged**
