### PR TITLE
(Add) Freeleech based on size threshold

### PR DESCRIPTION
**Pull request by LostRager**
Adds the ability to activate or deactivate automatic freeleech on torrents uploaded that meet a certain threshold set by the owner.

### CODE REVIEW

**Comment by HDVinnie** [comment]
I think this would be better off as a dashboard option where you can set conditions for FL or DU on torrents automatically. Using this as a base would be great. https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/2411

@Roardom thoughts?

**Comment by Obi-Wana** [comment]
How about having it like this in a fist step and refactor it to a dashboard later?

**Comment by HDVinnie** [comment]
I honestly feel like this is what we're trying to avoid anymore. Im not trying to push out contributors as there very welcome and much needed but in this case there is a more flexable and complete way to build this system out. If we merge as is then its just something we will have to revisit again and do a complete refactor....

**Comment by Obi-Wana** [comment]
You got an argument with this, indeed. Rgr, then lets touch it once and do it the clean way.

**Comment by FuNFooKaS** [comment]
could this be fixed up for V7?

**Comment by LostRager** [comment]
If you want it to work exactly how its laid out in the pr.

You can f.ex add this here:

```
if (config('torrent.size_freeleech') == true && $torrent->size >= \config('torrent.size_threshold')){
    $torrent->free = 100;
    $torrent->save();
}
```

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/6ed14c67142092a7a7aafbc4b680e89e776550be/app/Http/Controllers/TorrentController.php#L377

and this f.ex. here:

    if (config('torrent.size_freeleech') == true && $torrent->size >= \config('torrent.size_threshold')){
        $torrent->free = 100;
    }

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/6ed14c67142092a7a7aafbc4b680e89e776550be/app/Http/Controllers/API/TorrentController.php#L244

**Comment by FuNFooKaS** [comment]
This is not working in  latest unit3d?

**Comment by LostRager** [comment]
> This is not working in latest unit3d?

This is not needed anymore. https://unit3d.dev/dashboard/automatic-torrent-freeleeches

**Comment by FuNFooKaS** [comment]
I liked it, i for the life of me can not seem to get a proper regex to take in the new one.

**Pull request closed without merging**
